name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installer Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les tests
        run: pytest -v

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image Docker
        run: docker build -t taskflow:latest .

  security:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image Docker
        run: docker build -t taskflow:latest .

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@e07451d2e059ed86c2870430ea286b3a9e0bf241
        with:
          version: v0.68.2
          cache: true

      - name: Scan avec Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: taskflow:latest
          severity: HIGH,CRITICAL
          exit-code: "0"
          skip-setup-trivy: true
